branch-defaults:
  master:
    environment: ambivan-env
environment-defaults:
  ambivan-env:
    branch: null
    repository: null
global:
  application_name: Ambivan
  default_ec2_keyname: aws-ambivan-key
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
